### ISSUE TITLE
ftgmac is still not detecting link if cable plugged in after BMC is booted

### ISSUE THREAD

**Issue by nkskjames** [openbmc/linux#61] opened 2016-03-15 02:06 UTC
Here are steps to fail:
1. LAN cable plugged
2. BMC booted
3. Setup network
[network works fine]
4. turn off AC
5. unplug LAN cable
6. turn on AC
7. BMC boots
8. Plug in cable
9. LAN is not enabled (ftgmac100: NCSI dev is down)

**Comment by gwshan** [comment] 2016-03-17 02:17
Did we issue below commands after step (8) ? By the way, who from IRC channel I can get more info?

ifconfig eth0 down && ifconfig eth0 up

**Comment by nkskjames** [comment] 2016-03-17 03:52
ifconfig eth0 down && ifconfig eth0 up does make network work.  The expectation from end user is that when the cable is plugged the link should come up on its own though.  Is that not correct?  I will see if we can get person who reported this on IRC.

**Comment by gwshan** [comment] 2016-03-17 04:18
No, when the cable is plugged, the network interface won't be up automatically. When MAC has NCSI is enabled, we don't have a PHY attached. That means we don't have a thread monitoring the link status and wake up the MAC when link is ready. With NCSI, we have to issue "ifconifg ethx down && ifconfig eth0 up" after the cable is plugged.

The problem here is the above command doesn't help after cable is plugged.

**Comment by nkskjames** [comment] 2016-03-17 17:41
"The problem here is the above command doesn't help after cable is plugged."
not sure what you mean. ifconfig down/up does work after cable is plugged.

NC-SI specifies an async event notification for things like link state change.  Please see section 6.7 in: http://www.dmtf.org/sites/default/files/standards/documents/DSP0222_1.0.1.pdf.   If that doesn't work, it is not unusual to poll for link status from what I understand.

**Comment by gwshan** [comment] 2016-03-21 10:34
Yeah, you're correct that the AEN packet will be sent upon link-down event. The NCSI stack will try to choose another available channel if existing. Otherwise, the NCSI interface is down and I guess it's the case. When NCSI stack receives AEN on link-up event, it tries to choose an available channel for communication if we don't have one yet.

I'll try to reproduce this issue on local BMC tomorrow or a bit later...

**Comment by nkskjames** [comment] 2016-04-11 16:24
What is the status of this?

**Comment by gwshan** [comment] 2016-04-12 00:48
I don't have a chance to reproduce it locally. I will try it later of this week or early of next week.

**Comment by anoo1** [comment] 2016-04-15 21:52
Customer reported same issue today. Any progress on recreating?

**Comment by gwshan** [comment] 2016-04-16 01:47
Not yet, I'll continue on this next Monday when sitting around the BMC :-)

**Comment by gwshan** [comment] 2016-04-18 02:47
I'm using "dev-4.3" branch as the base source code to debug the issue. Also the hardware platform is Palmetto. The experiment I did is as below and it should match with the experiment that James did.

- Unplug the cable;
- Load the kernel and boot it;
- ifconfig eth0 xxx.xxx.xxx.xxx, and we should see the interface is down;
- Plug the cable and issue command "ifcofig eth0 down && ifconfig eth0 up". The network is back to service.

One thing I observed from James saw is: Reconfiguring the network interface after plugging the network cable will bring the network back. I also added some code to print the AEN packet received on plugging or unplugging the network cable. However, I never see a AEN packet received.

**Comment by nkskjames** [comment] 2016-04-20 23:01
So what next?

**Comment by apopple** [comment] 2016-04-20 23:09
@gwshan it sounds like you are expecting to receive an AEN packet but aren't? Does the device driver rely on getting this packet? If so we should try and debug why you aren't getting them.

**Comment by gwshan** [comment] 2016-04-21 08:49
Yes, I expect to receive AEN indicating link change on the active channel and I don't receive it when unplugging the ethernet cable. I added some printk() in the NCSI stack and print the received AEN packet. I don't see it.

**Comment by mdmillerii** [comment] 2016-04-26 13:15
Do you get an AEN when the link drops?
Do you have a poller to make sure the NCSI selection is still active? (see 6.8.3)

**Comment by Kenthliu** [comment] 2016-04-27 02:29
@gwshan Did you try wireshark to check the packet?

**Comment by gwshan** [comment] 2016-04-27 23:41
@Kenliu when the NCSI interface is down, no frames will be received on the
interface. So there're no packets seen on wireshark. As I mentioned before,
I add some printk() in the source code of the NCSI stack that dumps the
packets on receiving AEN packet. Nothing was dumped.

In current design, the NCSI and other (like ARP/IP) packets are transmitted
or received through same channel. When opening the NCSI, the channel is
enabled and NCSI packets exchanged with remote end to setup the NCSI
interface. the channel is going to be disabled if that fails. Otherwise,
the channel is enabled and monitor on AEN packets. In order to support
polling mechanism, we need separate channels for NCSI and other packets. It
will introduce huge changes to current farady driver implementation and I
need evaluate after finishing work at hand. On the other hand, there is one
additional question: when the cable is unplugged, can we probe the
situation by NCSI (Get Link Status packet) response without issue? I need
check it out later as well.

Another thing I'm not satisfied with current NCSI stack is: all available
package/channel are probed when opening up the ethernet interface. However,
once the NCSI topology is finalized for once and it's not going to change
dynamically. I need improve it later.

2016-04-27 12:29 GMT+10:00 KenLiu <notifications@github.com>:

**Comment by jk-ozlabs** [comment] 2016-04-28 03:28
@nkskjames If we can get some info from Broadcom about the absence of that AEN message, that'd be helpful for us.

**Comment by Kenthliu** [comment] 2016-04-28 03:44
Yes. I already sent an issue to Broadcom. Waiting for the response.
![case](https://cloud.githubusercontent.com/assets/15260220/14874807/7cfcea0c-0d36-11e6-9d16-c8159b075a55.jpg)

**Comment by Kenthliu** [comment] 2016-05-06 12:37
Hi @gwshan and @jk-ozlabs 
Response from Broadcom. Do you agree this?
![aen](https://cloud.githubusercontent.com/assets/15260220/15073126/571a8354-13ca-11e6-9aea-c3316b9e34ca.jpg)

**Comment by gwshan** [comment] 2016-05-06 14:12
Hi Ken, Thanks for checking with broadcom on this. It sounds the case. I
will enable that explicitly with AEN enable
command packet. Prior to that, I have to introduce some changes to farady
driver so that we can always receive
ingress NCSI packets.

However, the statement you had isn't always true according to the
experiment I did. Initially, I never send a AEN enable
packet to target NCSI channel. With a PCI slot reset through GPIO PINs, I
still can receive AEN packet from far end.

2016-05-06 22:37 GMT+10:00 KenLiu <notifications@github.com>:

**Comment by gwshan** [comment] 2016-05-07 01:35
Thanks again for Ken's feedback from Broadcom. I added some code in the
NCSI stack to enable AEN explicitly by transmitting a AEN enablement packet
on the active channel. I can receive AEN packet from far end (broadcom)
when unplugging the cable. However the AEN packet is still missed when
plugging the cable. I assume something is missed in the code. I will
continue the debugging.

2016-05-07 0:12 GMT+10:00 Shan Gavin <shan.gavin@gmail.com>:

**Comment by gwshan** [comment] 2016-05-09 01:59
A pachset sent to maillist for review. The issue is fixed by it. I had below testing with the patchset on palm4-bmc. Everything looks good:

   * From uboot, download the kernel image;
   * Unplug the ethernet cable;
   * From uboot, boot the kernel image;
   * Configure the ethernet interface when the kernel boots up completely.
     The NCSI interface should be down;
   * Plug the cable, the NCSI interface is up automatically. The interface
     is pingable from external.

**Comment by shenki** [comment] 2016-05-24 01:14
I think this is resolved. Please re-open if it happens again.

**Closed by shenki** 2016-05-24 01:14 UTC
Labels: bug
